### ISSUE TITLE
Repeater Book Integration

### ISSUE THREAD

**Issue by Jonthetrombonist** [ArkansasRepeaterCouncil/website#620] opened 2019-06-09 00:15 UTC
**Is your feature request related to a problem? Please describe.**
      No.

**Describe the solution you'd like**
     A way of sending updates from the website onto Repeater Book to update repeater listings there automatically. This will alleviate the dual updating that the repeater owners have been doing.

**Describe alternatives you've considered**
       Manually adding/changing the data as updates are made.

**Additional information**
      I'm uncertain at this time whether or not Repeater Book has an API for doing just that, however it does have export features into Chrip, RT Systems, and I believe as a comma separated file. Garrett, KD6KPC and the Repeater Book site owner, would probably be willing to help in getting some sort of automatic method going.

**Comment by JoshuaCarroll** [comment] 2019-06-10 14:58
I not opposed to this, but I would need to know that they are open to the idea.  I would prefer that they consume our API to pull data on demand and only cache it in case the API is inaccessible for some reason - but I imagine that's a pipe dream.  

Do you want to reach out to them and see if they would be interested in an API?  I'm not going to send them a file, and they'll find scraping the site difficult (this is by design).

**Comment by Jonthetrombonist** [comment] 2019-06-10 23:23
I'll definitely reach out to them.

Repeater Book doesn't scrape data (unlike the other popular service which
does) from the repeater directories, but it is mostly crowd sourced from
the repeater owners, heavy users, and travelers reporting of the status.In
fact the "other service" was caught scrapping data from Repeater Book (cough
cough)
<https://www.repeaterbook.com/index.php/2016-04-07-21-08-49/9-blog/18-imitation-is-the-sincerist-form-of-flattery>


I'm the repeater book Admin for Arkansas. Any updates from* the users* have
to be checked by eye for erroneous entry, facts, etc to ensure the info is
as correct as possible. I'm sure with it polling an API this check can be
avoided, as the info will be set in stone truth.

 Due to the large popularity nation wide of Repeater book I think it would
be of great service to get updated data from the council. I definitely will
reach out to them, probably this weekend, and see if I can't get something
brewing.

Thanks for the hard work Josh!
73
K5DVT

**Comment by JoshuaCarroll** [comment] 2019-06-12 16:23
Sounds like a plan.  I'll wait until we hear back from you.

**Comment by JoshuaCarroll** [comment] 2019-06-17 19:47
Have you heard anything back about an API?

**Comment by Jonthetrombonist** [comment] 2019-07-03 22:46
Sorry It's taken this long to reply. For some reason this email was put in
my updates folder and was under a pile of University and College spam. TBH
I haven't gotten a hold of Garret, the man with the beard about the API.
Work and College Enrollment caught me by the blind side lol. I have a long
holiday weekend this week, so I'll see if I can't get the emails rolling

-Jon, K5DVT

**Comment by JoshuaCarroll** [comment] 2020-01-09 04:26
Any news?

**Comment by Jonthetrombonist** [comment] 2020-01-09 14:59
Unfortunately no.

I got busy with my Freshman year of College.

 Garret, the webmaster, resolved issues with Google maps keyless usage and
the repeater plotting of the website. Instead of an overlay like " For
development only" it would crash the webpage. Things are better, still not
100%. I'm know this has to do with Google Maps changing the way their API
works, but I'm not entirely sure what it would be the map solution. Does
work 'Most' of the times.

Garret also has just implemented a new feature to also list GMRS repeaters
(But in a separate database). (Which Arkansas needs some if you happen to
know any open GMRS repeaters...)

I'm not sure if this project really is going to come to fruition or fizzle
out.

-Jon, K5DVT
ARC Director

**Comment by JoshuaCarroll** [comment] 2020-01-09 16:04
This ticket has been open for seven months, and RepeaterBook still does not support this type of interaction.  Closing this ticket.

**Closed by JoshuaCarroll** 2020-01-09 16:04 UTC
Labels: enhancement, question
