### ISSUE TITLE
Exception while calling web service for repeater data

### ISSUE THREAD

**Issue by hiram-maxim** [ArkansasRepeaterCouncil/website#70] opened 2019-01-28 21:44 UTC
### Message
> The remote server returned an error: (500) Internal Server Error.

### Help link
> 

### Source
> System

### Stack trace
>    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
>    at System.Net.WebClient.DownloadString(Uri address)
>    at System.Net.WebClient.DownloadString(String address)
>    at Repeater.LoadPublic(String repeaterId) in e:\kunden\homepages\21\d553920072\www\ARC-website\App_Code\Repeater.cs:line 121

Repeater ID: 111'"`

**Comment by JoshuaCarroll** [comment] 2019-01-29 00:53
Duplicate of #66

**Closed by JoshuaCarroll** 2019-01-29 00:53 UTC
